name: Build and Push dnsapi-server Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build_dnsapi-server-${{ github.ref }}    # 按分支分组
  cancel-in-progress: true                    # 有新触发时取消同组在途运

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push dnsapi-server Docker Image
    # 支持手动构建和提交信息中存在关键字 build_dnsapi_server
    if: >
      ${{
        github.event_name == 'workflow_dispatch' ||
        contains(github.event.head_commit.message, 'build_dnsapi-server') ||
        contains(github.event.head_commit.message, 'build_all')
      }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dnsapi-server/GithubActions.Dockerfile
          push: true
          tags: ${{ secrets.ALIYUN_REGISTRY }}/iproute/dnsapi-server-aliyun:latest
